[2024-11-19 14:22:21,043][train][INFO] - [Starting Epoch 0]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:05<00:00,  1.82s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.27s/it]
[2024-11-19 14:22:24,568][train][INFO] - Best Checkpoint saved with score: 0.6542507112026215
[2024-11-19 14:22:26,510][train][INFO] - [Starting Epoch 1]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.30s/it]
[2024-11-19 14:22:29,041][train][INFO] - Best Checkpoint saved with score: 0.43820470571517944
[2024-11-19 14:22:31,071][train][INFO] - Best Checkpoint saved with score: 0.43312913179397583
[2024-11-19 14:22:33,267][train][INFO] - Best Checkpoint saved with score: 0.3899126350879669
[2024-11-19 14:22:33,315][train][INFO] - [Starting Epoch 2]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:07<00:00,  2.34s/it]
[2024-11-19 14:22:35,921][train][INFO] - Best Checkpoint saved with score: 0.17124392092227936
[2024-11-19 14:22:38,077][train][INFO] - Best Checkpoint saved with score: 0.15704889595508575
[2024-11-19 14:22:40,163][train][INFO] - Best Checkpoint saved with score: 0.13452725112438202
[2024-11-19 14:22:40,218][train][INFO] - [Starting Epoch 3]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                 | 2/3 [00:05<00:02,  2.86s/it]
[2024-11-19 14:22:42,839][train][INFO] - Best Checkpoint saved with score: 0.033218901604413986
[2024-11-19 14:22:44,939][train][INFO] - Best Checkpoint saved with score: 0.007913447916507721
[2024-11-19 14:22:47,184][train][INFO] - Best Checkpoint saved with score: 0.0012435147073119879
[2024-11-19 14:22:47,243][train][INFO] - [Starting Epoch 4]
Traceback (most recent call last):                                                                                                                                                                                                                                                      
[2024-11-19 14:22:51,749][train][INFO] - Best Checkpoint saved with score: 0.0002511025231797248
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/ImageFile.py", line 554, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agesp/hackatum/ml_stuff/train.py", line 321, in <module>
    train()
  File "/home/agesp/hackatum/ml_stuff/train.py", line 292, in train
    log_images_to_wandb(model, val_dl, global_step)
  File "/home/agesp/hackatum/ml_stuff/train.py", line 165, in log_images_to_wandb
    "image_pred": [wandb.Image(grid_test)],
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/wandb/sdk/data_types/image.py", line 180, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/wandb/sdk/data_types/image.py", line 337, in _initialize_from_data
    self._image.save(tmp_path, transparency=None)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/Image.py", line 2605, in save
    save_handler(self, fp, filename)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 1488, in _save
    ImageFile._save(
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/ImageFile.py", line 558, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/ImageFile.py", line 584, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/ImageFile.py", line 554, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agesp/hackatum/ml_stuff/train.py", line 321, in <module>
    train()
  File "/home/agesp/hackatum/ml_stuff/train.py", line 292, in train
    log_images_to_wandb(model, val_dl, global_step)
  File "/home/agesp/hackatum/ml_stuff/train.py", line 165, in log_images_to_wandb
    "image_pred": [wandb.Image(grid_test)],
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/wandb/sdk/data_types/image.py", line 180, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/wandb/sdk/data_types/image.py", line 337, in _initialize_from_data
    self._image.save(tmp_path, transparency=None)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/Image.py", line 2605, in save
    save_handler(self, fp, filename)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 1488, in _save
    ImageFile._save(
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/ImageFile.py", line 558, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/home/agesp/miniconda3/envs/hackatum/lib/python3.9/site-packages/PIL/ImageFile.py", line 584, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
